import random

def userGuess(x):
    #User guesses a number generated by computer
    rand_num = random.randint(1,x)
    guess = 0
    while guess != rand_num:
        guess = int(input(f"Guess a random number between 1 and {x}: "))
        if guess < rand_num :
            print("Sorry guess is too low ")
        elif guess > rand_num :
            print("Sorry guess is too high")
    print(f"Yay! you have guessed {rand_num} correctly")

def computerGuess():
    #Computer guesses a number by continous feedback by user
    x = int(input("Enter the number for computer to guess: "))
    low = 1
    high = x
    feedback = ''
    while feedback != 'c':
        if low != high :
            guess = random.randint(low,high)
        else:
            guess = low
        feedback = input(f'Is {guess} too high (H), too low (L), or correct (C)').lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    print(f"I guessed {guess} correctly!!")

computerGuess()